language: node_js
node_js:
  - "12"

branches:
  only:
    - master
script:
  - ./node_modules/@angular/cli/bin/ng lint
  - ./node_modules/@angular/cli/bin/ng build --prod --base-href https://t-palmer.github.io/travis-demo/

deploy:
  provider: s3
  access_key_id: AKIASTPGXLAM33CQBCT2
  secret_access_key: $AWS_SECRET_KEY
  bucket: "stnimmerwapp"
  skip_cleanup: true
  upload-dir: dist/webapp

notifications:
  email:
    recipients:
      - mail@stnimmerlein.de
    on_success: always # default: change
    on_failure: always # default: always
