language: node_js
node_js:
- '12'

branches:
  only:
  - master

script:
- ./node_modules/@angular/cli/bin/ng lint
- ./node_modules/@angular/cli/bin/ng build --prod --base-href https://stnimmerlein.de/travis/webapp/

after_success:
- scp -o StrictHostKeyChecking=no -r dist/webapp/* root@stnimmerlein.de:/var/www/html/travis/webapp 

notifications:
  email:
    recipients:
    - mail@stnimmerlein.de
    on_success: always
    on_failure: always

before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_229ae95ad2c9_key -iv $encrypted_229ae95ad2c9_iv
  -in deploy-key.enc -out ./deploy-key -d
- chmod 400 ./deploy-key
- ssh-add ./deploy-key
